#!/bin/bash

# Branchr Widget Setup Script
# This script helps set up App Groups for the widget extension

echo "🎯 Branchr Widget Setup Guide"
echo "=============================="
echo ""
echo "📱 STEP 1: Create Widget Extension Target"
echo "1. In Xcode: File → New → Target"
echo "2. Choose: Widget Extension"
echo "3. Name: BranchrWidgetExtension"
echo "4. Language: Swift"
echo "5. Uncheck 'Include Configuration Intent'"
echo "6. Click Finish"
echo "7. When asked to 'Activate Scheme,' choose Cancel"
echo ""
echo "📱 STEP 2: Replace Default Files"
echo "1. Replace default BranchrWidget.swift with our implementation"
echo "2. Replace default BranchrWidgetBundle.swift with our implementation"
echo "3. Add SharedModels.swift to the widget target"
echo ""
echo "📱 STEP 3: Set Up App Groups"
echo "1. Select Branchr (main target) → Signing & Capabilities"
echo "2. Click + Capability → App Groups"
echo "3. Add: group.com.joedormond.branchr"
echo "4. Do the same for BranchrWidgetExtension target"
echo ""
echo "📱 STEP 4: Build Widget Extension"
echo "1. Select BranchrWidgetExtension scheme"
echo "2. Build (Cmd+B) - don't run, just build"
echo ""
echo "📱 STEP 5: Test Widget"
echo "1. On simulator/device: Long press home screen"
echo "2. Tap + → Search 'Branchr' → Add widget"
echo ""
echo "✅ Widget Features:"
echo "- Mode-aware display (Ride, Camp, Study, Caravan)"
echo "- Dynamic colors based on active mode"
echo "- Live stats (distance, duration, calories)"
echo "- Active indicator (green/gray dot)"
echo "- Two sizes: Small and Medium"
echo ""
echo "🔧 Technical Details:"
echo "- App Groups: group.com.joedormond.branchr"
echo "- Timeline updates: Every 10 minutes"
echo "- Mode persistence: Syncs with main app"
echo "- Fallback data: Shows placeholder if no ride data"
echo ""
echo "Press Enter when you've completed the Xcode setup steps..."
read -r
